package com.saviynt.identitybot.Util;

public class Constants {
	
	public static final String GLOBAL_SCRIPT_DATA = "GlobalScriptData";
	public static String STOP_VIDEO_FILE = "stopVideo.bat";
	public static String RECORDED_SCRIPTS_PATH = "recordedScripts";
	public static String RECORD_VIDEO_PATH = "recordedVideos";
	public static String CONVERTED_SCRIPTS_PATH = "convertedScripts";
	public static String PLAYBACK_SCRIPTS_PATH = "playbackScripts";
	public static String PLAYBACK_VIDEOS_PATH = "playbackVideos";
	public static String FILECONTENT_TEMP = "FileContent_Temp_";
	public static String FILECONTENT_TEMP_PY = "test_";
	public static String S3_BUCKET = "s3_bucket";
	public static String SCRIPT_STORE_LOCAL = "LOCAL";
	public static String SPACE = " ";
	public static String csvNewLine = "\n";
	public static String DOT_JAVA = ".java";
	public static String DOT_CLASS = ".class";
	public static String DOTPY = ".py";
	public static String DOT_BAT = ".bat";
	public static String DOTSAH = ".sah";
	public static String SUFFIX = "/";
	public static String UNDER_SCORE = "_";
	public static String FORWARD_SLASH = "\"";
	public static String WEB = "WEB";
	public static String CLI = "CLI";
	public static String PYWIN_PARAMS = "pywinParams";
	public static String PYWIN = "PYWIN";
	public static String PYTEST = "PYTEST";
	public static String DESKTOP = "DESKTOP";
	public static String COMMON = "COMMON";
	public static String JOBID = "JobId";
	public static String REASON = "reason";
	public static String IMPORTTYPE = "importType";
	public static String FILETYPE ="fileType";
	public static String SCRIPTS = "scripts";
	public static String RECORD_RUNTIME_SCRIPT = "cmd /c start /wait cmd.exe  /k powershell -NoExit  Start-Transcript -Path ";
	public static String START_VIDEO_RUNTIME_SCRIPT = "cmd /c start /min /wait powershell.exe ffmpeg -f gdigrab -i desktop -framerate 32 -vcodec libx264 ";
	public static String EXECUTE_BAT_FILE_RUNTIME_SCRIPT = "cmd /c start /wait cmd.exe  /k powershell type"; 
	public static String FOR_F_TOKENS_SCRIPT = "for /F \"tokens=*\" %%A in (";
	public static String DOT_TXT_DO_SCRIPT = ".txt) do ";
	public static String E_A_N_SCRIPT = " -e \"%%A\" \n";
	public static String PS_C_SCRIPT = "PS C.*>";
	public static String DOTTXT = ".txt";
	public static String MYSQL = "mysql";
	public static String DOTCSV = ".csv";
	public static String HIDDEN_DOT_TXT = "_hidden.txt";
	public static String UTF_8 = "utf-8";
	public static String COBOT_HOME = "COBOT_HOME";
	public static String COBOT_PROP_FILENAME = "application.properties";
	public static String USERNAME_KEY = "{\"username\":\"";
	public static String PASSWORD_KEY = "password\":\"";
	public static String ADMIN = "admin";
	public static String PASSWORD = "{noop}password";
	public static String USER = "USER";
	
	public static String ACCOUNT_ID_PATH = "accountIdPath";
	public static String SSM_TASK_ID = "Call1.message.value[0].taskid";
	public static String DATE_FORMAT = "dateFormat";
	public static String RESPONSE_COLS_TO_PROPS_MAP = "responseColsToPropsMap";
	public static String NAME = "name";
	public static String CONNECTION = "connection";
	public static String URL = "url";
	public static String HTTP_METHOD = "httpMethod";
	public static String POST = "POST";
	public static String HTTP_CONTENT_TYPE = "httpContentType";
	public static String APP_SLASH_JSON = "application/json";
	public static String FILE_NAME = "filename";
	public static String DATA = "data";
	public static String SEARCH_DATA = "searchdata";
	public static String SCRIPT_TYPE = "scriptType";
	public static String HTTP_PARAMS = "httpparams";
	public static String BODY = "Body";
	public static String HTTP = "http://";
	public static String CALL_BACK_URL = "CallBackURL";
	public static String FILE_NAME_R = "FileName";
	public static String REMOTE_IP = "remoteIp";
	public static String PARALLELEXECUTION_STATUS = "parallelexecution";
	public static String FORMAT = "format";
	public static String AGENT_IP = "AgentIP";
	public static String RECORD_VIDEO = "recordVideo";
	public static String RUNTEST = "runTest";
	public static String DOTMP4 = ".mp4";
	public static String TASKID = "taskid";
	public static String TASKKEYTOUPDATE = "taskKeyToUpdate";
	public static String UPDATETYPE = "updatetype";
	public static String PROVISIONING_METADATA = "provisioningMetadata";
	public static String COMMENTS = "comments";
	public static String COMPLETETASK = "completetask";
	//public static String SSM_VAR_TASKID = "${arsTasks.id}";
	public static String SSM_VAR_TASKID = "0";
	public static String AUTHORIZATION = "Authorization";
	public static String BASIC_AUTHORIZATION = "Basic YWRtaW46cGFzc3dvcmQ=";
	public static String HTTPPARAMS = "httpParams";
	public static String HTTP_HEADERS = "httpHeaders";
	public static String CALL = "call";
	public static String MSG = "msg";
	public static String PROVISIONING = "provisioning";
	public static String TRUE = "true";
	public static String FALSE ="false";
	public static String API_V5_COMPLETETASK = "/api/v5/completetask";
	public static String API_V5_UPDATETASK ="/api/v5/updateTasks";
	public static String API_V5_TESTCONNECTION = "/api/v5/testConnection";
	public static String API_LOGIN = "/api/login";
	public static String ERROR_SSM_CONNECTION = "Identity Bot server is down.";
	public static String ERROR = "Error";
	public static String FILE_CONTENT = "fileContent";
	public static String FILENAME = "fileName";
	public static String ROOTDIR = "rootDir";
	public static String EXECUTE_DOT_MODE = "execute.mode";
	public static String CMD_EXE = "cmd.exe ";
	public static String STATUS = "status";
	public static String SUCCESS = "success";
	public static String MESSAGE = "message";
	public static String VALID_SUCCESS = "Validated Successfully.";
	public static String _ERROR = "error";
	public static String FILE_CREATION_ERROR = "Temp File cannot be created.";
	public static String FILE = "File";
	public static String CLI_PARAMS = "cliParams";
	public static String DESKTOP_PARAMS = "desktopParams";
	public static String FILE_SAVE_SUCCESS = "File Saved Successfully.";
	public static String DATA_NOT_FOUNT = "Not data found";
	public static String FAIL = "fail";
	public static String EMPTY_JSON = "{}";
	public static String EMPTY_ARRAY = "[]";
	public static String EMPTY = "";
	public static String SLASH_N = "\n";
	public static String SLASH_C = "/c";
	public static String SLASH_IM = "/im ";
	public static String SLASH_K = "/k";
	public static String POWERSHELL_EXE = "powershell.exe";
	public static String POWERSHELL = "powershell";
	public static String TASKKILL = "taskkill ";
	public static char OPEN_CURLY_BRASES = '{';
	public static char CLOSE = ')';
	public static char SEMICOLON = ';';
	public static char SLASHR = '\r';
	public static String GREATER_THAN_OPERATOR = ">";
	public static char CLOSE_CURLY_BRASES = '}';
	public static String SEMI_COLON = ";";
	public static String DOUBLE_OPEN_CURLY_BRASES = "{{";
	public static String DOUBLE_CLOSE_CURLY_BRASES = "}}";
	public static String AND_OPERATOR = "&";
	public static String COMMA = ",";
	public static String DOT_STAR = ".*";
	public static String COLON = ":";
	public static String ACTIVE = "Active";
	public static String INACTIVE = "Inactive";	
	public static String MACHINE_IS_NOT_UP = "Machine is not up";	
	public static String SNO = "sno";
	public static String AGENT_NAME = "agentName";
	public static String AGENT_ID = "agentId";
	public static String IPADDRESS = "ipAddress";
	public static String LASTUPDATEDTIMESTAMP = "lastUpdatedTimestamp";
	public static String DATEFORMAT = "yyyy-MM-dd HH:mm:ss";
	public static String CONTENT_TYPE = "Content-Type";
	public static String ACCEPT = "Accept";
	public static String APPLICATION_JSON = "application/json";
	public static String APPLICATION_OCTET_STREAM = "application/octet-stream";
	public static String ACCESS_TOKEN = "access_token";
	public static String BEARER = "Bearer ";
	public static String APPLICATION_X_WWW_FORM_URLENCODED = "application/x-www-form-urlencoded";
	public static String CD = "cd ";
	public static String EXIT_1 = "exit 1";
	public static String SERVLET_CONTAINER = "servlet-container";
	public static String CATALINA_HOME = "catalina.home";
	public static String WEBAPPS = "/webapps/";
	public static String WEB_INF_LIB = "/WEB-INF/lib/*";
	public static String JAVA_CLASS_PATH = "java.class.path";
	public static String OS_NAME = "os.name";
	public static String WIN = "win";
	public static String JAVAC_CP = "javac -cp ";
	public static String OUTPUT = "OUTPUT";
	public static String PS = "PS ";
	public static String USERNAME = "username";
	public static String _PASSWORD = "password ";
	public static String WEBDRIVER_CHROME_DRIVER = "webdriver.chrome.driver";
	
	public static String TOKEN_ERROR_MSG = "SSM Token is not generated";
	public static String UNAUTHORIZED_MSG = "Invalid Credentials";
	public static String FORBIDDEN_MSG = "Syntax error";
	public static String APPNAME = "appname";
	public static String AppName="appName";
	public static String APPLICATION_PATH = "applicationpath";
	public static String APP_PATH = "apppath";
	

	
	public static String OPERATING_SYSTEM_NAME = System.getProperty("os.name");
	public static String WINDOWS_OS = "Windows";
	public static String MAC_OS = "Mac";
	
	public static String ACCESS_DENIED ="Invalid credentials";
	public static String NOT_RECOGNIZED_COMMAND ="Unable to find external internal commands";
	public static String UNKNOWN_DATABASE ="Database not found";
	
	public static String BOT_SERVER ="BOT Server";
	
	public static String ON ="on";
	public static String OFF ="off";
	
	public static String CHROME ="chrome";
	public static String MOZILLA ="mozilla";
	public static String IE ="ie";
	public static String OPERA ="opera";
	public static String MICROSOFTEDGE ="microsoftedge";
	public static String SAFARI ="safari";
	
	public static String COMMON_FOLDER ="common_methods";
	public static String COMMON_SCRIPTS ="common_scripts";
	public static String COMMON_METHOD_FILE ="AppSpecificMethods.java";
	
	public static String CLI_POPUP_MESSSAGE ="Saviynt Identity Bot is recording...";
	
	public static String ERROR_0="Can't trigger run from SSM. \"Agent is Null\"";
	public static String ERROR_1="Wrong combination: Load Balance is ON and Parallel execution ON . Please toggle Load Balance Off in properties file, restart the tomcat and run scripts again";
	public static String ERROR_2="Parallel execution is only for Web applications. Please run CLI/Desktop scripts after completion of web.";
	
	public static String MODULE_WEB = "Web";	
	public static String MODULE_CLI = "CLI";	
	public static String MODULE_DESKTOP = "Desktop";	
	public static String MODULE_API_JAVA = "API-Java";	
	public static String MODULE_API_PYTHON = "PYTEST";
	
	public static String PYTHON_DEFAULT_IMPORTS = "pythonDefaultImports.py";
	
	public static String MODULE_NAME = "moduleName";	
	public static String TYPE_OF_TEST = "typeOfTest";
	public static String DOT_PY = ".py";

}
